#!/usr/bin/env php
<?php

defined('ROOT_PATH') || define('ROOT_PATH', realpath(__DIR__));

foreach ([
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php'
         ] as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOAD', $file);
        break;
    }
}

unset($file);

if (!defined('COMPOSER_AUTOLOAD')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require COMPOSER_AUTOLOAD;

\EntityGenerator\Cli\Command::run();